### ISSUE TITLE
Contributing to this library

### ISSUE THREAD

**Issue by toomuchdesign** [MiroDojkic/react-clickable#5]
Hi @MiroDojkic,
I was about to extract the "clickable/a11y compliant element" logic from a project I'm currently working on to a standalone component when I found your project.

It has a lot of potential but it looks quite abandoned. 😃Is it still maintained and open to contributions? If you agree, I'd like to review and update a bit the current logic, bundling configuration and tests.

I also found interesting the approach taken in `StopPropagation` component. The main goal is to stop the propagation of nested `click` and `keyDown` + `enter` of `spacebar` events, right?

Are you aware of any further pain point I should consider for the development of this project?

Cheers!

**Comment by MiroDojkic** [comment]
Hi @toomuchdesign,

Indeed, I didn't have time to keep up with the library maintenance although it's usable as is.
We've been using it on several projects and didn't really have the need to update the library as it serves the purpose - didn't have any troubles with using it either.

I agree with you and I would actually really like that. I'd be happy to help you out with anything you need too, if any. :)

Regarding `StopPropagation` component, you completely got it.

Cheers! 🍻

**Comment by toomuchdesign** [comment]
Hi @MiroDojkic, thank's for your quick reply!
This is in brief what I'd like to focus on:

### Generic setup
- [x] declare proper peerDependencies
- [x] update RollupJS configuration to not bundle external libraries
- [x] remove `dist` folder from version control
- [x] setup FlowJS
- [ ] revamp docs
- [x] GitHub's PR's / issues templates
- [ ] Auto format code with `prettier` on pre-commit?

### Component specific
- [x] provide `tabIndex` and `role` as props
- [ ] Add [Coveralls](https://coveralls.io/) integration
- [ ] Add Travis integration
- [x] Mixed feelings about `ariaLabel` & `className` declared as empty strings (and not `undefined`) by default
- [x] provide support to both`onClick` and `onMouseDown` events
- [x] fix `StopPropagation`'s `onKeyDown` method (`e` vs. `event`)
- [ ] Since they are stateless, rewrite both component as a pure functions 😍

What do you think about it? Anything else?

Cheers! Ciao! 🍻

**Comment by MiroDojkic** [comment]
@toomuchdesign 
I like first two suggestions in generic setup.
Not sure how I feel about the third though, `dist` folder provides UMD build for anyone using `bower` or similar?

Regarding component everything seems great. 👌 

Thanks for the effort!

**Comment by toomuchdesign** [comment]
Ciao @MiroDojkic!
As for `bower`, `react-clickable` has currently no support for it.

As for the `UMD` build which can be directly consumed by any browser, I'm not suggesting of eliminating it but to simply upload it in the NPM registry along with an `es` and `cjs` build. Once there it will be consumable using a package manager like `npm` or `yarn` or via [unpkg](https://unpkg.com/#/), too!

I'd borrow the most of the setup from [`Redux`](https://github.com/reduxjs/redux) in order to make sure that we don't step away from the best practices.

Would you also agree integrating this project with [Travis](https://travis-ci.org/) and [Coveralls](https://coveralls.io/)?

The first will make sure that **every single release builds and has green unit tests** while the second will make sure that **test coverage doesn't drop** and provide us with a test coverage **badge**.

![screen shot 2018-07-04 at 15 01 42](https://user-images.githubusercontent.com/4573549/42278469-3b2ffab8-7f9b-11e8-93ce-d5fbb142d366.png)

**They are both free for open source projects**. You can access them with your GitHub credential and connect this repository to the tools they provide.

I'll make an early PR in the following days to start discussing about what I did and what you'd like to do.

Catch up soon. Cheers!

**Comment by MiroDojkic** [comment]
@toomuchdesign 
That seems to me like the right way to go.
I actually remember thinking about using [Microbundle](https://github.com/developit/microbundle) at some point, but if it's easier for you to extend current Rollup config it's all the same to me.

Yes, I liked using Travis in the past and Coveralls seems pretty cool. I'm looking forward to see the PR! 🙂

Cheers!

**Comment by toomuchdesign** [comment]
Superseded by #6.
